# Font
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.0

# Transparency and background
background_opacity 0.90
# background #2e3440

# Cursor
# cursor #88c0d0
# cursor_text_color #2e3440

# Window padding
window_padding_width 10

# Nord color scheme
# foreground #d8dee9
# background #2e3440
# selection_foreground #2e3440
# selection_background #88c0d0

# black
# color0  #3b4252
# color8  #4c566a

# red
# color1  #bf616a
# color9  #bf616a

# green
# color2  #a3be8c
# color10 #a3be8c

# yellow
# color3  #ebcb8b
# color11 #ebcb8b

# blue
# color4  #81a1c1
# color12 #81a1c1

# magenta
# color5  #b48ead
# color13 #b48ead

# cyan
# color6  #88c0d0
# color14 #8fbcbb

# white
# color7  #e5e9f0
# color15 #eceff4

# Tabs (in case you open multiple)
# active_tab_foreground   #2e3440
# active_tab_background   #88c0d0
# inactive_tab_foreground #d8dee9
# inactive_tab_background #3b4252

# Behavior
confirm_os_window_close 0
enable_audio_bell no


# BEGIN_KITTY_THEME
# Gruvbox Dark Hard
include current-theme.conf
# END_KITTY_THEME