add_newline = false

format = "$os$directory$git_branch$git_status$character"

[os]
format = "[$symbol](bold blue) "
disabled = false

[os.symbols]
Arch = ""

[directory]
style = "bold cyan"
format = "[$path]($style)[$read_only]($read_only_style) "
truncation_length = 2
truncate_to_repo = true
home_symbol = " ~"
read_only = " 󰌾"
read_only_style = "bold red"

[git_branch]
disabled = false
format = "[$symbol$branch]($style) "
symbol = " "
style = "bold purple"
truncation_symbol = "…"

[git_status]
disabled = false
format = "([$all_status$ahead_behind]($style)) "
style = "bold red"

stashed = "󰏗"
ahead = "󰁝"
behind = "󰁅"
diverged = "󰹹"
conflicted = "󰀨"
deleted = "󰆴"
renamed = "󰁕"
modified = "󰏫"
staged = "󰐕"
untracked = "󰞋"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold cyan)"
